### ISSUE TITLE
Inquiry about the paper' doi or accurate title.

### ISSUE THREAD

**Issue by wyy-csu** [hamedqm/MCMC_Inversion#1]
Thanks you for providing the dataset. I wonder the paper' doi or accurate title. Because I can't find the paper by searching the title you provided.
Thanks again.

**Comment by hamedqm** [comment]
Hi there, The paper is under review, so whenever the paper gets published I will add doi to it.

**Comment by wyy-csu** [comment]
Thanks for your response. I will continue following your updates.
